cameras/urls.py
from django.conf.urls import url

from . import views

app_name = 'cameras'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^faces/$', views.faces, name='faces'),    
    url(r'^clean/$', views.clean, name='clean'),  
    url(r'^activate/$', views.activate, name='activate'),     
    url(r'^schedule_for_deactivation/$', views.schedule_for_deactivation, name='schedule_for_deactivation'),     
    url(r'^kill/$', views.kill, name='kill'),     
]

persea/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cameras/', include('cameras.urls')),
]

# from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# urlpatterns += staticfiles_urlpatterns('', (
#     r'^static/(?P<path>.*)$',
#     'django.views.static.serve',
#     {'document_root': settings.STATIC_ROOT}
# ))

cameras/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

from django.db.models.signals import post_save
from django.dispatch import receiver

from .tasks import *
from persea.celery import app
from ip_cameras import ipCamera

import logging
import os

# Get an instance of a logger
LOG = logging.getLogger(__name__)

ACTIVE = 0
SCHEDULED_FOR_DEACTIVATION = 1
DEACTIVE = 2

class Camera(models.Model):
    name = models.CharField(max_length=255, default='camera')
    url = models.CharField(max_length=255)
    init_time = models.DateTimeField('initialised', auto_now_add=True)
    frame_counter = models.IntegerField(default=0)
    task_id = models.CharField(max_length=255)
    status = models.IntegerField(default=DEACTIVE)
    fps = models.CharField(max_length=10, default='0 fps')

    def __str__(self):
        return '{0} {1}'.format(self.name, self.url)

    def activate(self, *args, **kwargs):
        LOG.info('initialising camera {0}'.format(self))

        # create face directory in /static/cameras
        static_dir = os.path.join(settings.BASE_DIR, 'static')
        cameras_dir = os.path.join(static_dir, 'cameras')
        camera_dir = os.path.join(cameras_dir, 'cam_{0}'.format(self.id))
        if not os.path.exists(camera_dir):
            os.makedirs(camera_dir)

        # start task        
        res = start_streaming_task.delay(self.id, self.name, self.url)
        self.task_id = res.id
        self.status = ACTIVE
        self.save()

    def schedule_for_deactivation(self, *args, **kwargs):
        LOG.info('stopping camera {0}'.format(self))
        self.status = SCHEDULED_FOR_DEACTIVATION
        self.save()

    def kill(self, *args, **kwargs):
        LOG.info('killing camera {0}'.format(self))
        self.status = DEACTIVE
        self.save()
        # kill all running tasks
        LOG.info('killing {0}'.format(self.task_id))
        r = app.control.revoke(str(self.task_id), terminate=True)#, signal='SIGKILL')
        LOG.info('killed {0}'.format(r))

# @receiver(post_save, sender=Camera)
# def initialise_ip_camera(sender, instance, **kwargs):
#     LOG.info('initialise_ip_camera signal received')
#     LOG.info('{0}'.format(instance))

#     # start task
#     res = start_streaming_task.delay(instance.url, instance.name)
#     intance.task_id = res.id
#     instance.save()


    # ip_cameras.append(camera)

    # pickle.dump(ip_cameras, open(absolute_path, 'wb'))
 

cameras/views.py
from django.shortcuts import render, redirect

from models import *
from persea.celery import app
from django.conf import settings

import pickle
import logging
LOG = logging.getLogger(__name__)
import os

import glob

PATH = os.getcwd()

def index(request):
    LOG.info('index')
    cameras = Camera.objects.all()
    # absolute_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'cameras.obj')

    # LOG.info(os.path.exists(absolute_path))

    # ip_cameras = pickle.load(open(absolute_path, 'rb'))

    return render(request, 'cameras/cameras.html', {'cameras' : cameras})

def add(request):
    LOG.info('add request')
    if request.POST:
        name = request.POST.get('name', None)
        url = request.POST.get('url', None)
        if name and url:
            LOG.info('{0} {1}'.format(name, url))
            camera = Camera(name=name, url=url, frame_counter=0, fps='0 fps').save()
            LOG.info(camera)
            camera.start()
            LOG.info('saved')
    return redirect('/cameras')

def faces(request):
    LOG.info('shows faces')
    camera_id = request.GET.get('camera_id', None)
    static_dir = os.path.join(settings.BASE_DIR, 'static')
    cameras_dir = os.path.join(static_dir, 'cameras')
    camera_dir = os.path.join(cameras_dir, 'cam_{0}'.format(camera_id))
    file_name_query = os.path.join(camera_dir, 'frame_*')

    LOG.info(file_name_query)
    found_paths = glob.glob(file_name_query)
    LOG.info(found_paths)
    paths = []
    for path in found_paths:
        paths.append(path.replace(settings.BASE_DIR, ''))
    context = {'paths' : paths, 'camera': Camera.objects.get(id=camera_id)}
    return render(request, 'cameras/faces.html', context)

def clean(request):
    LOG.info('clean')

    cameras_dict = {}
    for camera in Camera.objects.all():
        # kill
        camera.status = DEACTIVE
        camera.save()

        # Collect duplicates in database
        if not camera.url in cameras_dict:
            cameras_dict[camera.url] = []
        cameras_dict[camera.url].append(camera.id)

    # Remove duplicate urls in database 
    for url, list_of_ids in cameras_dict.iteritems():
        if len(list_of_ids) > 1:
            for camera_id in list_of_ids[1:]:
                LOG.info('Camera with id {0} is scheduled for removal'.format(camera_id))
                Camera.objects.get(id=camera_id).delete()

    return redirect('/cameras')

def activate(request):  
    # initialise all tasks
    for camera in Camera.objects.all():
        camera.activate()
    return redirect('/cameras')

def schedule_for_deactivation(request):
    # Deactivate all tasks
    for camera in Camera.objects.all():
        camera.schedule_for_deactivation()
    return redirect('/cameras') 

def kill(request): 
    for camera in Camera.objects.all():
        camera.kill()    
    return redirect('/cameras')

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>{% block title %}Persea Technologies {% endblock %}</title>
    {% block headcss %}{% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="section">
        <div class="row">
          <div class="col s9"><a href="/cameras"><h3>Persea Technologies</h3></a></div>
          <div class="col s3">
<!--             <button data-target="feedback-modal" class="waves-effect waves-light btn modal-trigger">Got Feedback?</button> -->
          </div>
        </div>
        <div>
          <div id="feedback-modal" class="modal">
            <div class="modal-content">
              <h4>We <3 feedback</h4>
              <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                  <i class="mdi-content-send right"></i>
                </button>
              </form>
            </div>
            <div class="modal-footer">
              <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
          </div>
        </div>
        {% block content %}{% endblock %}
      </div>
    </div>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
    {% block extrabody %}{% endblock %}
  </body>
</html>

templates/cameras/cameras.html
{% extends "base.html" %}

{% block title %} Persea Technologies {% endblock %}

{% block headcss %}
  <style>
    .errorlist{
      color:#ff0000;
    }
  </style>
{% endblock %}


{% block content %}
<h4>Registered Ip Cameras</h1>
<ul>
{% for camera in cameras %}
    <li>
      {% if camera.status == 0 %} A {% endif %} 
      {% if camera.status == 1 %} S {% endif %}
      {% if camera.status == 2 %} D {% endif %}
    	{{ camera.fps }} 
      <a href="/cameras/faces?camera_id={{camera.id}}">{{ camera.name }}</a>
     	initalised at {{ camera.init_time }}
    </li>
{% endfor %}
</ul>

<a href="/cameras/activate" data-target="feedback-modal" class="waves-effect waves-light btn modal-trigger">Activate all</a>
<a href="/cameras/schedule_for_deactivation" data-target="feedback-modal" class="waves-effect waves-light btn modal-trigger">Schedule for deactivation</a>
<a href="/cameras/kill" data-target="feedback-modal" class="waves-effect waves-light btn modal-trigger">Kill all</a>
<a href="/cameras/clean" data-target="feedback-modal" class="waves-effect waves-light btn modal-trigger">Clean DB</a>
<br><br>


<h4>Register New Ip Camera</h1>

<form action="{% url 'cameras:add' %}" method="post">
{% csrf_token %}
	Name <input type="text" name="name" value="" />
	URL <input type="text" name="url" value="" />
<button type="submit" data-target="feedback-modal" class="waves-effect waves-light btn modal-trigger">Register</button>

</form>

{% endblock %}

templates/cameras/faces.html
{% extends "base.html" %}

{% block title %} Persea Technologies {% endblock %}

{% block headcss %}
  <style>
    .errorlist{
      color:#ff0000;
    }
  </style>
{% endblock %}


{% block content %}


<h3>Camera parameters</h3>
<img src="{{ camera.url }}" width="400">
<ul>
	<li>Camera ID: {{ camera.id }} </li>
	<li>Name: {{ camera.name }}</li>
	<li>URL: {{ camera.url }}</li>
	<li>Initialised: {{ camera.init_time }}</li>
	<li>Thread task ID: {{ camera.task_id }}</li>
	<li>Frame counter: {{ camera.frame_counter }}</li>	
</ul>
<h3>Downloaded Faces : {{paths|length}}</h3>
<ul>
<li>
{% for path in paths %}
   <img src={{path}}>
{% endfor %}
</li>
</ul>


{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% block title %}Picha Feedback!{% endblock %}

{% block headcss %}
  <style>
    .errorlist{
      color:#ff0000;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <h3>Feedback</h3>
      <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
          <i class="mdi-content-send right"></i>
        </button>
      </form>
    </div>
  </div>
{% endblock %}

templates/tasks.html
{% extends "base.html" %}

{% block title %}Picha Tasks{% endblock %}

{% block headcss %}
  <style>
    .errorlist{
      color:#ff0000;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <h3>Tasks</h3>
      <ul>
      {% for task in tasks %}
          <li>{{ task }}</li>
      {% endfor %}
      <li>{{ another_tasks }}</li>
      <li>{{ all_tasks }}</li>
      </ul>
    </div>
  </div>
{% endblock %}